### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [frigg/atom-frigg-runner-status#5]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`1.0.3`) of this package:

1. Use Workspace::getTextEditors instead
1. Use Workspace::observeTextEditors instead
1. Use Workspace::onDidAddTextEditor or Workspace::observeTextEditors instead.
1. Use ::getPaths instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by relekang** [comment]
All should be fixed now and released in 1.1.0 :tada:

**Comment by benogle** [comment]
Thanks!
